rand-brandes_adap-sampl_centrality: betweenness.o fibheap.o readgml.o main_rand-brandes_adap-sampl_centrality.o
	g++ betweenness.o fibheap.o readgml.o main_rand-brandes_adap-sampl_centrality.o -o rand-brandes_adap-sampl_centrality
fibheap.o: fibheap.h fibheap.cpp
betweenness.o: betweenness.h betweenness.cpp
readgml.o: readgml.h readgml.cpp
main_rand-brandes_adap-sampl_centrality.o: readgml.h betweenness.h main_rand-brandes_adap-sampl_centrality.cpp
